### ISSUE TITLE
cospend: Adding a project with wrong URL fails although UI suggest valid URL

### ISSUE THREAD

**Issue by hubx** [mayflower/PayForMe#38]
Sorry for spamming you with issues. Just trying to use the app with some friends :) 

While adding a cospend project I used the URL given by cospend (Copied to clipboard via Password protected access)

https://example.com/apps/cospend/loginproject/projectid
and password

The UI shows a green check mark and lets you add an invalid project. The project afterwards shows up as valid in the project list, but bills and members are empty.

The app construct the correct URL itself. Therefore server address should be just the server part, without the resource location
https://example.com - the example in the textfield suggests that, however it was not clear to me 

Can you extract servername and projectid from the absolute URL?

Adding via the QR code cospend provides also works. However it is harder to share to friends via messenger

**Comment by Hustenbonbon** [comment]
Hi, 

first of all: No worries, I am happy about people using the app and even more happy about feedback!

In PayForMe 1.X there were some users reporting problems with pasting links, so I tried to smartly disassemble all possible strings. It looks here like this doesn't work in your specific case.

The format of strings you provide is the one that Cospend v1.X uses, so I would try to avoid deprecating it. 

I try extracting projectId, servername and passwortd from the absolute URL in https://github.com/mayflower/PayForMe/blob/master/PayForMe/Util/Util.swift lines 177 and following (used in https://github.com/mayflower/PayForMe/blob/master/PayForMe/Views/Projects/Manual/AddProjectManualViewModel.swift for example). If you want to have a look and find the bug yourself, you are very welcome, otherwise I'll have a look sometime in the future.

Underneath the QR code in cospend, you'll find the string encoded in the QR code. If you share that via messenger, people having the app installed should be able to add the project automatically by clicking on it

**Comment by hubx** [comment]
> first of all: No worries, I am happy about people using the app and even more happy about feedback!
:clap: I might have sent you have the into wrong direction though...

I just realized that there is a **Paste Link** at the top. I thought this is plain text, it does not look like an actionable button to me at all.

To clarify what I did before, I went into the Server Address field and pasted the URL directly into there, which seem to not trigger the smart disassembly :sweat_smile:  I don't know if you can trigger disassembly behavior if the value of server address changes?

I think what would have helped me here is, if the text would look more like an actionable button, similar to the "Add Project Button", which a caption like "Import from Clipboard" that made it clear it is different from merely pasting into the texfield.

> The UI shows a green check mark and lets you add an invalid project. The project afterwards shows up as valid in the project list, but bills and members are empty.

is what confused me the most. The constructed URL was probably something like https://example.com/apps/cospend/loginproject/projectid/projectid/password and on my nextcloud this HTTP 302 redirects to /login. 

If I look at the Copied to clipboard via Password protected access site I get a login field with prefilled input password field that gets submitted on javascript pageload (https://gitlab.com/eneiluj/cospend-nc/-/blob/master/src/login.js#L18). I don't know if cospend provides a better API to verify if URL/password are correct?

**Comment by cestmoimeme** [comment]
Hi there
I try to ligin but it doesn't work : with the url, it doesn't "split" the right way (but my nextcoud is into a folder https://mynextcloud.com/directory , I guess this is the problem ?
Same when I try to flash the qrcode : the screnn just freeze and nothing

Is there still develop on this projet ? I hope so , 'cause cospend is really good , and a pity I can't use it on my iphone

thanks for the job anyway ! I hope you will keep going on :)

**Comment by Hustenbonbon** [comment]
Hi, yes there is still occasionally development on the project. I’ll look at it in the next days. Which Cospend verspinn are you using?
The issue might probably be that your Nextcloud is in a subdirectory, I’ll have a look if I can find an easy fix

**Comment by cestmoimeme** [comment]
Hi ! glad to hear about this project !
I use the last cospend : 1.4.3 and it works fine ... I hope you can fix it ;)
Thank you so much

**Comment by Hustenbonbon** [comment]
Thanks to @Logarythms ' pull request, this issue should be resolved now. The fix is currently in App Store review, and should be in the store in 1-2 days
